### ISSUE TITLE
zero-shot test dataset of TCGA BRCA

### ISSUE THREAD

**Issue by credithana** [mahmoodlab/CONCH#13]
I noticed that the paper mentions conducting a zero-shot test on the TCGA BRCA data by subsampling from the TCGA-RCC data. Could you please clarify how it was possible to conduct the test using data from a different organ? If this is a typo, could you explain the method used to sample the 150 data points?

Thanks!

**Comment by fedshyvana** [comment]
it's sampled from TCGA BRCA, 75 slides per class (IDC and ILC) while ensuring slides from the same patient are not simultaneouly in Train and test.
