### ISSUE TITLE
Quality assessment of image-text pair descriptions

### ISSUE THREAD

**Issue by huangzuhao** [mahmoodlab/CONCH#15]
How to judge the quality of the conch model's embedding calculations（image_embedings @ text_embedings.T） for images and text descriptions?

**Comment by fedshyvana** [comment]
typically this would be posed as a retrieval task, where you have a held-out set of image / caption pairs, and you use image to try to retrieve its corresponding caption from your whole database of captions and vice versa. You can quantify the performance via metrics like Recall@K.
