### ISSUE TITLE
implementation of Zeroshot cross-modality retrieval

### ISSUE THREAD

**Issue by fengweie** [mahmoodlab/CONCH#2]
Thank you for your excellent work, I am interested in the implementation of Zeroshot cross-modality retrieval, is it possible to release this part of the code? Thank you for your work.

**Comment by fedshyvana** [comment]
Hi, thanks for the interest, you can find our example code here: https://github.com/mahmoodlab/CONCH/blob/main/notebooks/zeroshot_retrieval_example.ipynb
