### ISSUE TITLE
model training and fine-tuning

### ISSUE THREAD

**Issue by Fclef** [mahmoodlab/CONCH#8]
Hi, 

Thanks for sharing your work! Can you please also share the training setup of CONCH? I want to fine-tune CONCH so it can properly caption my H&E data. I noticed CONCH is very similar to openAI CoCa, is there any sample code so I can use their training script to train CONCH?

Tim

**Comment by fedshyvana** [comment]
Hi, I think directly finetuning CONCH using their training script might kinda of difficult given that their repo (i assume you are talking about openclip) has undergone a lot of version changes when I was working on this project. If you want to finetune CONCH, I would suggest trying to just plug the vision encoder backbone (which is just a standard ViT) into their repo, it's likely the piece that's gonna make the most difference.
